### ISSUE TITLE
V57033F include all numeric column types for Logical Views

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#30]
## Logical View Numeric Tests

Table VTL157033F has already been created. 
These are the new Columns:
![image](https://github.com/lansa/db-regression/assets/4089160/71254462-1b19-4825-8262-990d9e3a8d24)

### Logical Views
Create Logical Views over each of the columns.
Invalid Column Types for Logical View:  BINARY, VARBINARY
Valid column types for logical view: SIGNED, DECIMAL, INTEGER 1, 2, 4, 8
Logical View (Index) has already been created for these columns:
`BIFINT1A, BIFN0700A, BIFN0702A, BIFP1504A`
Still require 4 more Logical Views over the remaining columns (BLOB index not required)

### Test Data
Test data already created and testing algorithm in place for numeric fields. 
Expected test result data needs to be updated as tests are added.
See subroutine `AddTestData`. There are sections for each test value with a comment like `* Search <1>`, `* Search <2>, etc`. 
Each `mthFunc_Search_...` method requires a separate list created to store the expected results for each logical view used by the specific test e.g. `#wLTestResultGenericSigned_Decimals`. And add in the following code for each `Search <n>`:
```
* Generic Signed_Decimals Results (Edit to match test name)
#LF_Test_Result_L157033FI1 #LF_Test_Result_L157033FI2 #LF_Test_Result_L157033FI4 #LF_Test_Result_L157033FI8 #LF_Test_Result_L157033FP #LF_Test_Result_L157033FN := 0
#LF_Test_Result_L157033FB := 0
#LF_Test_Result_L157033FPD #LF_Test_Result_L157033FND := 0
#LF_Test_Result_L157033FD #LF_Test_Result_L157033FT #LF_Test_Result_L157033FDT := 0
Add_Entry To_List(#wLTestResultGenericSigned_Decimals) /* Edit to use correct list */
```
Then run the test which will throw an error at the point of executing `mthDoTestResults`. Copy the actual results into the appropriate lines above. Re-compile, re-run and repeat for each `Search <n>`.

Also note that some of the test data has separate *BACKWARDS & *FORWARDS DESCENDING results and possible differences when executing on IBM i. In the first instance you presume that both of these extra contexts have the same results. Only if a difference is found then a separate value is saved for either or both contexts.
```
* *** Generic Signed Results
#LF_Test_Result_L157033FI1 #LF_Test_Result_L157033FN := 16
#LF_Test_Result_L157033FI2 #LF_Test_Result_L157033FI4 #LF_Test_Result_L157033FI8 #LF_Test_Result_L157033FP := 0
#LF_Test_Result_L157033FPD #LF_Test_Result_L157033FND := 16
Add_Entry To_List(#wLTestResultGenericSigned)
* BACKWARDS
If (#LF_Remote_Platform *EQ I)
#LF_Test_Result_L157033FPD #LF_Test_Result_L157033FND := 1
#LF_Test_Result_L157033FI1 #LF_Test_Result_L157033FN := 16
Else
#LF_Test_Result_L157033FPD #LF_Test_Result_L157033FND := 17
#LF_Test_Result_L157033FI1 #LF_Test_Result_L157033FN := 32
Endif
Add_Entry To_List(#wLTestResultGenericSignedBackwards)
* FORWARDS DESCENDING
If (#LF_Remote_Platform *EQ I)
#LF_Test_Result_L157033FI1 #LF_Test_Result_L157033FN := 32
#LF_Test_Result_L157033FPD #LF_Test_Result_L157033FND := 2
Else
#LF_Test_Result_L157033FI1 #LF_Test_Result_L157033FN := 64
#LF_Test_Result_L157033FPD #LF_Test_Result_L157033FND := 34
Endif
Add_Entry To_List(#wLTestResultGenericSignedForwardsDescending)
```
### Code
The current code has this type of structure:
At the top level in `mthDoSearch` are the calls to test each of the column types
```
#Com_Owner.mthSearch_By_Signed_Decimals( #LF_Test_Data #this_rc )
#Com_Owner.mthSearch_By_Signed( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Decimal_Decimals( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Decimal( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Integer1( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Integer2( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Integer4( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Integer8( #LF_Test_Data #this_rc )
```
The first task is to complete `mthSearch_By_Signed` by adding Logical Views for BIFINT2A, BIFINT4A and BIFINT8A and then providing the code to access those Logical Views.
The second task is to add routines in the same manner as has been done for `mthSearch_By_Signed_Decimals` and `mthSearch_By_Signed`. There are various layers behind each of the above routines which are all required when talking about duplication below.

`mthSearch_By_Decimal_Decimals` and `mthSearch_By_Decimal` are carbon copies of the first 2 routines, with appropriate comments and names changed. And of course using the matching Class for the parameter `#this_test_value`. Even the test results will be identical. 

In a similar manner `mthSearch_By_Integer1- 4` are carbon copies of `mthSearch_By_Signed` (They are all 'integer' column types).

The special column types, DATETIME, DATE, TIME, BOOLEAN, are not being added by this test. It has been left here as documentation for Issue #31 

At this level, e.g. `mthSearch_By_Signed_Decimals`, there is both a Generic and an Exact search - `mthFunc_Search_Generic_Signed_Decimals` and `mthFunc_Search_Exact_Signed_Decimals`. Even the column types that do not support Generic will have both, as the call must still work, it just works as if Generic(*YES) has not been specified.

For this example the next level down is `mthFunc_Search_Generic_Signed_Decimals`. 
The Class will require changing for `#this_test_value`:
```
Define_Map For(*INPUT) Class(#BIFN0702A) Name(#this_test_value)
```
The following will require appropriate equivalents for the `Count` and the `List`:
```
If (#LF_i > #LF_Test_Result_Generic_Signed_Decimals_Count)
#this_rc := ER
#Com_Owner.mthAdd_SubMsg( #this_rc #this_operation ('Test result ' + #LF_i.asString + ' missing from Test Result List') )
Return
Else
Get_Entry Number(#LF_i) From_List(#wLTestResultGenericSigned_Decimals)
Endif
```
And then finally there is this code for each Logical View thats relates to the column type:
```
* SIGNED(7,2).
#LF_View_Type := ' View Key: SIGNED(7,2)'
#Com_Owner.mthAdd_Msg( #this_rc (#LF_View_Type + ' ' + #this_operation) ('Key Value:' + #this_test_value.asString) )
Select Fields(#BIFN0702A) From_File(L157033FND) With_Key(#this_test_value) Nbr_Keys(*COMPUTE) Generic(*YES) Io_Status(#this_rc) Io_Error(*NEXT) Val_Error(*NEXT)
#LF_Func_L157033FND += 1
#Com_Owner.mthAdd_TraceMsg( #this_rc '' ('Result: ' + #BIFN0702A.asString) )
Endselect
#Com_Owner.mthAdd_SubMsg( #this_rc #this_operation ('On Logical View L157033FND. Rows = ' + #LF_Func_L157033FND.asString + ' Expected = ' + #LF_Test_Result_L157033FND.asString) )
If ((#this_rc = ER) *Or (#this_rc = VE))
#LF_Total_Errors += 1
Else
#this_rc := OK
Endif
```
The type of column will need changing, the Logical View name e.g. `L157033FND` in the 5 locations and the correct Field returned by the `SELECT` and when obtaining the result e.g. `#BIFN0702A`.

And the bottom level performs the tests for particular input data defined by `#this_test_value` and use that data for each type of Logical View Key that that  input data may be used with. For the enhancements the compatibilities are as follows:

Note that generic searches have additional tests for *BACKWARDS. This is due to there being a different path through the code that needs testing.

Input Data | Compatible Key Columns
-- | --
SIGNED no decimals | BIFN0700A, BIFP1500A, BIFINT1A, BIFINT2A, BIFINT4A, BIFINT8A
SIGNED with decimals | BIFN0702A, BIFP1504A
DECIMAL no decimals | BIFN0700A, BIFP1500A, BIFINT1A, BIFINT2A, BIFINT4A, BIFINT8A
DECIMAL with decimals | BIFN0702A, BIFP1504A
INTEGER 1 | BIFN0700A, BIFP1500A, BIFINT1A, BIFINT2A, BIFINT4A, BIFINT8A
INTEGER 2 | BIFN0700A, BIFP1500A, BIFINT1A, BIFINT2A, BIFINT4A, BIFINT8A
INTEGER 4 | BIFN0700A, BIFP1500A, BIFINT1A, BIFINT2A, BIFINT4A, BIFINT8A
INTEGER 8 | BIFN0700A, BIFP1500A, BIFINT1A, BIFINT2A, BIFINT4A, BIFINT8A

**Comment by ashtkumar2023** [comment]
Started analyzing this issue  
1)Created the indexes in VL IDe for
BIFINT2A - Ascending,Descending
BIFINT4A - Ascending ,Descending
BIFINT8A - Ascending ,Descending
BIFP1500A - Ascending  , Descending 

2)Inside the function V57033F  
Modifying the test cases to support  BIFINT2A ,BIFINT4A  ,BIFINT8A
Forwards, Backwards, forwards descending ,Backwards descending ,
