### ISSUE TITLE
V57033G include all non-numeric non-char column types for Logical Views

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#31]
Refer to Issue #30  
This only describes differences from V57033F

### Introduction

Table VTL157033G has already been created. 
These are the new Columns:
![image](https://user-images.githubusercontent.com/4089160/234503929-d727f0d5-a41c-4b20-9c0a-67f1eb3ed94b.png)

### Logical Views
Create Logical Views over each of the 4 columns (BLOB index not required)

### Test Data
Test data already created and testing algorithm in place.
Expected test result data needs to be updated as tests are added.
See subroutine `AddTestData`. There are sections for each test value with a comment like `* Search <1>`, `* Search <2>, etc`. 

### Code
V57033G already created, with no tests. Template code to be taken from V57033F to start the lowest levcel of tests e.g. `mthFunc_Search_Generic_DateTime`.

The current code has this type of structure:
At the top level in `mthDoSearch` are the calls to test each of the column types
```
Begin_Loop Using(#LF_i) To(#LF_Test_Key_Count)
Get_Entry Number(#LF_i) From_List(#wLTestKey)

#Com_Owner.mthAdd_SubMsg( #this_rc ('<' + #LF_i.AsString + '> Search Test: ' + *Quote + #LF_Test_Data.asString + *Quote) '' )

#Com_Owner.mthSearch_By_DateTime( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Date( #LF_Test_Data #this_rc )
* #Com_Owner.mthSearch_By_Time( #LF_Test_Data #this_rc )

If (#this_rc *NE OK)
Leave
Endif
End_Loop

If (#this_rc = OK)
* Just a single test value for Boolean. More about syntax checking than anything else.
* #Com_Owner.mthSearch_By_Boolean( True #this_rc )
Endif
```

Note that Boolean is a single iteration all by itself.

Finally there are the special column types, DATETIME, DATE, TIME, BOOLEAN, which will need writing from scratch, though much of the code can be used as a template.

Note that DateTime column accuracy must be limited to 24 to support the least accurate database servers - MSSQLS and SQLAZURE.

Input Data | Compatible Key Columns
-- | --
DATETIME | BIFDT26C, BIFDATEA, BIFTIMEA
DATE | BIFDT26C, BIFDATEA, BIFTIMEA
TIME | BIFDT26C, BIFDATEA, BIFTIMEA
BOOLEAN | BIFB001E

**Comment by ashtkumar2023** [comment]
Started analyzing

**Comment by ashtkumar2023** [comment]
@robe070 ,I will be creating the below Logical View [Indexes] :                                                                                     
1) L157033GB  - Boolean
2) L157033GD - Date
3) L157033GT  - Time .                                                                                                                                                             It  is mentioned above to not to create index for 'Blob' and hence I will not be creating it.

**Comment by robe070** [comment]
... and DATETIME

**Comment by ashtkumar2023** [comment]
Ok..I see the index for DATETIME is already created, but I will test and validate DATETIME in both Windows and IBMi.
![image](https://github.com/lansa/db-regression/assets/147069578/857886e9-1412-49bf-b76f-0324f2e3c433)
