### ISSUE TITLE
Table Attribute Testing - Convert Special Characters in Column Names

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#34]
Ref: [Table Attributes](https://docs.lansa.com/15/en/lansa015/index.htm#lansa/l4wtgu03_0045.htm#_Toc97285175?TocPath=Technical%2520Reference%2520Guide%257C3.%2520Tables%257C3.7%2520Table%2520Attributes%257C_____0)

Table attributes which are IBM i only are not to be tested. This includes Table Schema, Record Format Name, Alternate Collating Table, Share, Secure, Suppress IOM0034 Messages, Ignore Decimal Errors, IOM Required, IBM i High Speed Table, Auto Commit, CRTPF and CHGPF Parameter, and Database Table Trigger

### Convert Special Characters in Column Names
Create these objects
Object Type | Object Name | Description | Details
-- | -- | -- | --
Process | VTI0034 | Table Attribute Tests |  
Function | VI0034A | Issue #34 Test Case Driver |  
Function | VI0034C | Convert Special Characters |  
Table | @@#$ | Convert Special Characters | Columns as per Fields below
Field | #@#$ | Convert Special Characters | Numeric 7,0
Field | $$@# | Convert Special Characters | Numeric 7,0
Field | @@@@@@@@@@ | Convert Special Characters | Numeric 7,0

Add the Fields as columns to the table.

Insert 5 rows of test data in a similar manner to I0033.
Test the data similarly too.

**Comment by Netravati1205** [comment]
Reviewing Process , function ,Table and Fields to understand their properties.

**Comment by Netravati1205** [comment]
Created Process and function similar to I0033, and able to create the Table with special characters as column names.

Enhancing  the test cases for different scenario, also will add it as part of verifier to check the logs text file.

**Comment by robe070** [comment]
**Raise a PR immediately.** It gives me your starting point and makes comparison of your changes much easier.

**Comment by Netravati1205** [comment]
**https://github.com/lansa/db-regression/pull/66** - PR has been raised, please let me know the review comments if any.

**Comment by robe070** [comment]
Far too late. I asked for it immediately. For the reasons given.
