### ISSUE TITLE
Import Table Definitions

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#36]
Ref: [Import Table Definitions](https://docs.lansa.com/15/en/lansa015/index.htm#lansa/l4wtgu03_0830.htm#_Toc97285226?TocPath=Technical%2520Reference%2520Guide%257C3.%2520Tables%257C3.14%2520Import%2520Table%2520Definitions%257C_____0)

The focus here is on testing the OAM not on the actual importing of the table definition into LANSA. Table(s) will be created in each of the supported databases using SQL DD statements like CREATE TABLE... Thus the one script may be used to create the table in each supported database. Then that table is imported into LANSA for each supported database resulting in 5 or so different tables with similar structure and similar tests.

The table will have an example of every supported column type.

Add Test Data and test like #33

**Comment by Netravati1205** [comment]
https://github.com/lansa/db-regression/pull/83

**Comment by Netravati1205** [comment]
![image](https://github.com/lansa/db-regression/assets/122512451/877b145a-538d-4bd8-ac72-e9474757d640)

While delivering the imported table into LANSA01_P50PGMLIB getting warning saying "Compile will be bypassed for imported table table" so skipping test in  LANSA01_P50PGMLIB

Or let me know if this tests needs to be skipped in IBM-I

**Comment by robe070** [comment]
Skip test on IBMi. Use `mthGetExecutionType` documented in Getting Started Guide. Test `LF_Remote_Platform = 'I'`

**Comment by Netravati1205** [comment]
![image](https://github.com/lansa/db-regression/assets/122512451/2e28c01b-5fc3-4f5f-8473-a321a9cdc84b)

Its fails to find the imported table 'VTLI0036A' in the LF_Remote_Platform = 'I' as well , should I skip this test.

**Comment by robe070** [comment]
Also? Thats what you are already meant to be skipping. All these tables are Windows only. All have the same structure.
