### ISSUE TITLE
Batch Control

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#38]
Ref: [Batch Control](https://docs.lansa.com/15/en/lansa015/index.htm#lansa/l4wtgu03_0050.htm#_Toc97285200?TocPath=Technical%2520Reference%2520Guide%257C3.%2520Tables%257C3.9%2520Batch%2520Control%257C_____0)

### Objects
Object | Description |   |  
-- | -- | -- | --
VTI0038 | Process |   |  
VI0038A | Test Case Driver |   |  
VI0038C | Batch Control |   |  
VTLI0038C | Batch Control Items |   |  
VTLI0038D | Batch Control Accumulation |   | Copy of VTLI0038C
  |   |   |  

### Test Data
Generate data based on
BIFP0700A from 1 - 5
Loop BIFA040A from A - E within each BIFP0700A value.
BIFN0700A from 1 incremented for each row added
Accumulate the totals into a list which will mimic the results expected from VTLI0038D.

Use I0033 type of testing architecture, but just testing the one value of BIFN0700A.

**Comment by robe070** [comment]
Take note of this line in the Ticket description:
"Accumulate the totals into a list which will mimic the results expected from VTLI0038D"
As you insert into table C you are expected to mimic what will be in table D by doing ADDITION WITHIN the program.
And then compare those results with what actually is in Table D.
Instead, you have explicitly specified the expected values when testing. If more test rows were inserted into Table C it would invalidate all your tests.

**Comment by kiranbhattar** [comment]
I will amend the changes as suggested

**Comment by kiranbhattar** [comment]
I have made code updates as suggested. please review

**Comment by kiranbhattar** [comment]
As confirmed by @robe070 , the task is now marked as successfully completed.
Thank you
