### ISSUE TITLE
Programmer Commitment Control

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#39]
Ref: [Commitment Control](https://github.com/lansa/db-regression/wiki/Programmer-Commitment-Control-Explanation)
Ref: [Mixed Mode Commitment Control](https://docs.lansa.com/15/en/lansa015/index.htm#../../lansa065/content/lansa/laddsnbe_0010.htm#_Ref101243261)
Ref: [DBMS_OPTIMIZE](https://docs.lansa.com/14/en/lansa015/content/lansa/set_session_value.htm#:~:text=Technical%20Notes%20for%20Session%20Value%20DBMS_OPTIMIZE%3D)

Use test case 157033 as your template.

### Mixed Mode Commitment Control

Skip this test if DB Type = SQLANYWHERE

Note that Mixed Mode Commitment Control is switched on for all database types currently in use in the EPC150060 instance and later.

Whilst this area is important and testing is generally very limited, its not an area of the database layer which is intended to be altered.

The testing needs to focus on the LANSA level of commitment control, not on whether the database is isolating changes from different database users.

Requires 2 files. One with `Enable Commitment Control` = Yes (VTLI0039C), and one with `Enable Commitment Control` = No (VTLI0039D).

The structure of the test data will be different to 157033. For this test case it will be a case of issuing INSERT, UPDATE, DELETE and FETCH statements in an appropriate order:

VTLI0039C referred to as 'C' - for 'Commitment Control'. VTLI0039D referred to as 'D'.

Clear any existing data from C and D

INSERT C
ROLLBACK
INSERT D
**ROLLBACK**
FETCH C - check row does not exist
FETCH D - check row exists
DELETE D

INSERT C
COMMIT
INSERT D
**COMMIT**
FETCH C - check row exists
FETCH D - check row exists

DELETE C
ROLLBACK
DELETE D
**ROLLBACK**
FETCH C - check row exists
FETCH D - check row does not exist

INSERT D
DELETE C
COMMIT
DELETE D
**COMMIT**
FETCH C - check row does not exist
FETCH D - check row does not exist

INSERT C
COMMIT
INSERT D
**COMMIT**
UPDATE C
ROLLBACK
UPDATE D
**ROLLBACK**
FETCH C - check updated row does not exist
FETCH D - check updated row exists

UPDATE C
COMMIT
UPDATE D
**COMMIT**
FETCH C - check updated row exists
FETCH D - check updated row exists

### DBMS OPTIMIZE

Do this test for all DB Type, including SQLANYWHERE.

Use a table that is NOT under commitment control AND, separately, a table that IS under commitment control.

```
use set_session_value ( DBMS_OPTIMIZE BEGIN_SYNC_100 )
begin_loop from(1) to(101)
   insert fields(......) to_file(testfile)
   use set_session_value ( DBMS_OPTIMIZE SYNC_POINT )
end_loop
ROLLBACK
use set_session_value ( DBMS_OPTIMIZE END_SYNC )
* Test that row 100 is in table but 101 is not in table.
```

**Comment by robe070** [comment]
Comments regarding Database Type are in regard to the code you write. Your code needs to limit execution where its requested above. Like
'''
Skip this test if DB Type = SQLANYWHERE
'''
You need to code that. There are examples in some of the existing test cases.
You are not required to execute the test against all databases. Only execute against SQL Server and against SQLANYWHERE to ensure the test is skipped.
AZURESQL access is not enabled. 
ORACLE is a shared database that may be being used by the DevOps pipeline and so must not be used.

**Comment by kiranbhattar** [comment]
[Verifier_Test_Report.txt](https://github.com/lansa/db-regression/files/13933225/Verifier_Test_Report.txt)

**Comment by robe070** [comment]
I have modified the Mixed Mode Commitment Control tests to add the same ROLLBACK/COMMIT after Table D access that has been done after Table C access. You just need to copy the code put in after the C IO after the D IO.

**Comment by kiranbhattar** [comment]
the PR is now updated as suggested by reordering the methods as suggested.
