### ISSUE TITLE
Predetermined Join Columns

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#41]
Refer to [Predetermined Join Columns](https://docs.lansa.com/15/en/lansa015/index.htm#lansa/l4wtgu03_0170.htm#_Toc97285170?TocPath=Technical%2520Reference%2520Guide%257C3.%2520Tables%257C3.6%2520Predetermined%2520Join%2520Column%2520(PJC)%2520Definitions%257C_____0)

From your experience creating previous DB Regression test cases, create a new Function - VI0041C (copy of V57033F) and File VTLI0041C (copy of VTL157033F).
Design the test data to exercise and check the SELECT statements required to cover the following requirements:

PJC Type | Description
-- | --
Lookup | Specifies that the Predetermined Join Column will hold the value retrieved from the selected PJC Source Column in the accessed table. This option is only available when there is a 1:1 relationship between the tables. The Predetermined Join Column must be of the same type as the selected column.
Total | Specifies that the Predetermined Join Column is to hold the total of the selected PJC Source Column retrieved using the access route key. This option is only available when there is a 1:many relationship between the tables and the selected column is numeric.
Maximum | Specifies that the Predetermined Join Column is to hold the highest value of the PJC Source Column selected column in records retrieved using the access route key. This option is only available when there is a 1:many relationship between the tables and the selected column is numeric.
Minimum | Specifies that the Predetermined Join Column is to hold the lowest value of the selected PJC Source Column in records retrieved using the access route key. This option is only available when there is a 1:many relationship between the tables and the selected column is numeric.
Average | Specifies that the Predetermined Join Column is to hold the average value of the selected PJC Source Column in records retrieved using the access route key. This option is only available when there is a 1:many relationship between the tables and the selected column is numeric.
Count | Specifies that the Predetermined Join Column is to hold the count of the number of columns retrieved using the access route key. This option is only available when there is a 1:many relationship between the tables.

At least 3 tables are required to implement this test case. The table with the PJCs defined. The table with a 1:1 relationship with the PJC table. The table with a 1:many relationship with the PJC table.

PJC Type Lookup will require looking up a Decimal and a Char field type.
PJC Type Count will use any convenient column type
The remaining 4 PJC Types will use numeric Columns as follows: Decimal, Signed, Integer 2, Float

**Comment by robe070** [comment]
Looks good so far. You need to write the tests before you go any further. That is actually the goal of this ticket. Its not about using these features but testing the features work correctly.

**Comment by kiranbhattar** [comment]
thank you @robe070
