### ISSUE TITLE
Performance Test - Bind Variables

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#49]
Write a test case to be used by LANSA developer to obtain base line performance statistics and then database-specific SQL to act over that table using bind variables. By comparing the results the expected performance gain may be able to be ascertained for at least the particular test case, given the databases are each configured with varying CPU and RAM and network speed.

A LANSA table needs to be created with 1000 rows containing a numeric id, keyed and a char string thats not keyed. SELECT the char string column. E.g SELECT DESCRIPTION WHERE ID = #id
The LANSA code will simply execute a loop from 1 - 1000 with the SQL SELECT DESCRIPTION WHERE ID = 1, SELECT DESCRIPTION WHERE ID = 2, etc

Then native SQL needs to be written for all the Windows database types that LANSA supports:
SQL Server
Azure SQL
Oracle
SQL Anywhere
MySql

An example is provided for Oracle below, but it is not executing against the LANSA table. It needs to be changed to do that. Both scripts need to be written for every database: one using a literal, the other using a bind variable

#### The Performance Killer
Just to give you a tiny idea of how huge of a difference this can make performance wise, you only need to run a very small test:
Here is the Performance Killer ....

SQL> alter system flush shared_pool;
SQL> set serveroutput on;

declare
      type rc is ref cursor;
      l_rc rc;
      l_dummy all_objects.object_name%type;
      l_start number default dbms_utility.get_time;
  begin
      for i in 1 .. 1000
      loop
          open l_rc for
          'select object_name
             from all_objects
            where object_id = ' || i;
          fetch l_rc into l_dummy;
          close l_rc;
          -- dbms_output.put_line(l_dummy);
      end loop;
      dbms_output.put_line
       (round((dbms_utility.get_time-l_start)/100, 2) ||
        ' Seconds...' );
  end;
/
101.71 Seconds...

#### The Performance Winner:
Using a bind variable.

declare
      type rc is ref cursor;
      l_rc rc;
      l_dummy all_objects.object_name%type;
      l_start number default dbms_utility.get_time;
  begin
      for i in 1 .. 1000
      loop
          open l_rc for
          'select object_name
             from all_objects
            where object_id = :x'
          using i;
          fetch l_rc into l_dummy;
          close l_rc;
          -- dbms_output.put_line(l_dummy);
      end loop;
      dbms_output.put_line
       (round((dbms_utility.get_time-l_start)/100, 2) ||
        ' Seconds...' );
end;
/
1.9 Seconds...

**Comment by ashtkumar2023** [comment]
Started analyzing

**Comment by ashtkumar2023** [comment]
@spcelestials  is working on the SQL script part. Meanwhile,we will also create a new table and commit it asap .
