### ISSUE TITLE
163721 Save Log Files to S3 and Consolidate log file output into pipeline views

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#5]
Powershell script to save log files and results in S3 and return the summary log file and results into the Pipeline log file.

Log file location is s3://lansa-us-east-1/db-regression-test/logs/[LansaVersion]/[unique release id from pipeline]

Refer to https://github.com/lansa/db-regression/wiki

and

https://github.com/lansa/db-regression/wiki#pipeline

and the wiki pages on errors may also be useful

**Comment by yashita-accolite** [comment]
Hi @robe070 for SQL Server the log files are not present as specified at https://github.com/lansa/db-regression/wiki/Regression-Test-Log-Files
Can you please give more information for log files in Microsoft SQL Server.

**Comment by robe070** [comment]
ALL of the log files? None of them are where specified?

Which VM instance are you using?

**Comment by yashita-accolite** [comment]
Hi @robe070 
 For SQL SERVER, I was not able to find any, but for others also, the file path for result.txt doesnt exist.
I am using vm-instance id-> i-050c4fec3da2296dd

**Comment by robe070** [comment]
Please provide the SPECIFIC paths you are using. Maybe you've misinterpreted my description? Or maybe I've got it wrong.

**Comment by yashita-accolite** [comment]
eg: SQLANYWHERE, the path I am using is
,C:\Program Files (x86)\SQLANYWHERE\X_WIN95\X_LANSA\x_wbp\Compile\DBTEST\result.txt , using this path for SQL Server, mysql and IBMi  shows the error that the filepath doesn't exist

**Comment by yashita-accolite** [comment]
Hi @robe070 
Cannot find path 'C:\Program Files (x86)\ORACLE\lansa\lansa\ORACLE' because it does not exist.
I got this error while testing the script with ODBCORACLE, is this expected to not exist ?

**Comment by robe070** [comment]
Yes it's expected. The path is correct. Thank you for checking.

**Comment by yashita-accolite** [comment]
Hi @robe070, so is it expected to exist afterwards when the script is run from the actual pipeline,  or should I add a check( to see if the file  path exists) before writing logs into s3 to avoid this error(mentioned in last comment)

**Comment by robe070** [comment]
All paths should be tested and if it does not exist a warning needs to be sent using Write-Host
