### ISSUE TITLE
163722 Compile and Execute Test Cases

### ISSUE THREAD

**Issue by robe070** [lansa/db-regression#6]
Use the db-test.ps1 script to compile & execute the test cases.

This task is now about implementing this feature in the pipeline. There are no changes required in db-test.ps1

Architecture is described here: https://github.com/lansa/db-regression/wiki

And in particular the pipeline requirements are here: https://github.com/lansa/db-regression/wiki#pipeline

**Comment by robe070** [comment]
The git repo is already cloned into each of the configurations on the VM. See architecture for LANSA root folders.
The git repo is cloned into a particular place in each LANSA Root: `[Root]\lansa\VersionControl`. For example `c:\program files(x86)\LANSA\LANSA\VersionControl`. And the script would be run from `c:\program files(x86)\LANSA\LANSA\VersionControl\Scripts\db-test.ps1`

So this task is to create the pipeline and run the script from the appropriate directory depending on the database type(s) chosen to execute and optionally compile.

I gave you access to the VM so you could see run it manually and gain understanding of what you need to do through the pipeline.



So the script is run from

**Comment by rajiv1279** [comment]
How pipeline is linked with db-test.ps1 script.?
